### ISSUE TITLE
Incorrect for empty input

### ISSUE THREAD

**Issue by randombit** [mimoo/siphash#1]
There is an early return in case the input message is empty:

https://github.com/mimoo/siphash/blob/cfa2982da40a2c59a5855795e6501ae1edfa282e/src/lib.rs#L53

but the value returned is only correct for the key [0,1,2,3,...]

**Comment by mimoo** [comment]
I thought I was really clever when I wrote that line in the code. 

Anyway thanks for pointing this out :D

**Comment by mimoo** [comment]
fixed by https://github.com/mimoo/siphash/commit/f26f93f574a1972f852e3ab5a69abd4f38c9a02c
